Pavan-Kamthane/C_langauege_

- arithmatic.c
> c program added

- Find if You Are Adult or Not
Code in C for Finding if You are Adult or Not
> Code Added

- Recursion Program
> Recursion Program

- bubble_sort.c
Added C code for bubble sort algorithm @Pavan-Kamthane
> Added C code for bubble sort algorithm

- Arrays in C
> Create Arrays in C

- teddy1404/factorial.c
> teddy 1404

- calculation.c
> Added the Calculator.c

- pabitra0011/Reverse a string.c
I add a simple c program to reverse a string .please merge my pull request. this is my first open source contribution ever , I will try to add more c program releted to this repo.                Thank You.
> add code for reverse a string

- 2x2MatrixDeterminant.c
- Add Binary Numbers.c
- Print 1 to 100 numbers
- armstrong.c
- string.c
have a look on my repo to add some simple code of c programming
> added added some simple code of c programming

- vector.c
> vector code added

- Devansh042005
my first open source contribution.
> added to find if char. entered is uppercase or not

- fibonacci_search.c
> added fibonacci search

- Varunv003/Reversing-sentense-using-recurssion.c
hello,
this is my first Pr for Hactoberfest
> Recursive program to Reverse a sentence

- Reverse a number
> Create Reverse a number

- Christmas-tree-pattern-program.c
Hi there!  I added the christmas tree pattern program in your repo. Hope it'll get merged soon.
> Added Christmas tree pattern program

- vijayalaxmi23/array.c
- vijayalaxmi23/linkedlist.c
I have done the programs do check it once
> I have added two programs in the file please do check it

- binary_search.c
Added c program for binary search. issue #21
> Added C program.

- polynomial_multiplication.c
Please add my code to your repository with "hacktoberfest-accepted" label
> polynomial_multiplication

- .gitignore
- Array/MultiDimensional/sumOfSquareOfDiagonal.c
I have added C Program to add the square of the Diagonal Matrix 'Multidimensional' and also added .gitignore file as I have seen most of the people were pushing the binary file of their program as well.
> C program to add square of Diagonal in Matrix

- Tic-Tac-Toe/tictactoe.c
This program is a small game Tic Tac Toe in C programming, here two users can play this game and after completing the game program will show the winner user name. This program is created using by Two Dimensional Array.
> Tic Tac Toe Game

- electricitybillgenerator.c
A program where when you input no. of units of electricity consumed, gives your bill
> electricitybillgenerator.c

- arraymultiplication.c
Program to find the multiplication of 2d array
> arraymultiplication.c

- matrix addition
its a program to add 3 matrices
> 3 matrix addition

- Note Exchange
Here when the user will enter the amount he will get the number of each denomination(note) he can get.
> Note Exchange

- Vowelandconsonant.c
To identify wheather a letter is vowel or consonant
> Vowelandconsonant.c

- Multiplication.c
> Multiplication.c

- array.c
Please tag me accepted for hacktober fest 2022.
> Menu driven array program in C language

- hollowrectangle.cpp
Print hollow rectangle pattern.
> hollowrectangle.cpp

- C Patterns/pascaltriangle.cpp
> pascaltriangle.cpp

- palindrome.c
Check number palindrome or not. Please add with label hacktoberfest.
> palindrome.c

- yearmonthday.c
A program wherein if the user enter n number of days, then the code shows the number of year, months, and days.
> yearmonthday.c

- array_reverse.c
I added the code to reverse an array. Kindly merge it.
> Reverse an array

- INSERTION.c
- stack.c
Added Code For Insertion Sort.Please accept my pull request.
> Insertion Sort

- stationery bill
here the user will get price list of the items and when he enters the number of items taken he will get the bill.
> stationery bill

- linkedList/single/normal/delete_at_nthpos.c
Deleting node at certain position. Hacktoberfest
> delete node at certain position

- 2matrixsum.c
Program to do sum of two 3D matrix.
> 2matrixsum.c

- Basic_C/hello_world.c
> Basic C program added

- Sorting_in_C/Pigeonhole_Sort.c
> Added Pigeohole sort

- tower_of_hanoi.c
> Added Towers of Hanoi

- Factorial_Number.c
This program will calculate the factorial of a entered number.
> Factorial Of Number.c

- linear_search.c
I have shared my code in c language to perform linear search
> Linear_search

- Bibek Pant/percentageAndAverageCalculator.c
Hello sir, I have added a folder of my name [Bibek Pant] with a c program to calculate average marks and percentage of user-inputted marks. Please, check the program and approve if you feel okay. Thank you.
> percentage and average marks calculater of user inputted marks

- Calculator.cpp
Program to make a calculator in C++
> Calculator.cpp

- arrayreverse.cpp
> reversearray.cpp

- Hollow rectangle pattern
Created hollow rectangle pattern using c
> Create Hollow rectangle pattern

- arraylinearsearch.cpp
Program to find index of a element in array
> arraylinearsearch.cpp

- Quadraticroots.c
Program to find roots of a quadratic equation using Conditional Operator. Please merge
> Quadraticroots.c

- ConditionalOperator2.c
Program to check biggest of 3 number using Conditional Operator. Please merge
> ConditionalOperator2.c

- ConditionalOperator1.c
Program to check which alphabet is vowel or not using Conditional Operator.
> ConditionalOperator1.c

- C Patterns/butterfliy.c
Program to print pattern like Butterfly. Please merge
> butterfly.c

- Information_of_C
This contains the information of C programming language.
> Information_of_C

- C Recursion Examples/towerofhanoi.c
- gcd.c
Added the program to solve the tower of hanoi problem using recursion.
> created tower of hanoi program in c

- Linked List/linked_list.c
Please accept my PR with all necessary hacktoberfest labels
> All Operations of Linked list in c

- lcm.c
- rotate.c
I have added 2 C programs to find LCM and to rotate the digits of number
> Added 2 programs lcm.c and rotate.c

- Negative Number
Program runs until user enter a negative number
> Negative Number

- hello_world_C
- prime_number_C
- swapping_the_number_C
THis contains the code to print "hello world" in C language.
> hello_world_C

- prime_number_C
This contains the prime number code in C language.
> prime_number_C

- ListArmstrongnum.c
Program to print List of Armstrong numbers between 1 to n(user givenn num).
> ListArmstrongnum.c

- Digitssum.c
Program to do sum of digits in a number. Please merge
> DigitSum.c

- Summation.c
Program to do sum of a series like 1/1 +1/2 +1/3+........+ 1/n .
> Summation.c

- snake/snake.c
> Snake Game

- DeepaSubramanyam/Butterfly_Pattern.c
- DeepaSubramanyam/ChangeDateFormatToEUDateFormat.c
I have added C program for butterfly pattern. Thank you
> Add. Butterfly pattern

- Ram Kaminwar/ram.c
> Created New File 

- socialnet_trees.c
A BST based mini-implementation of social networks.
Implemented a social network system, which consists of  various users connected in a network of a non-linear structure.
> Added socialnet.c

- treeTraversal.c
This code contains the three types of traversal - Inoder, Preorder and Postorder traversal of a binary tree. For the issue #231
> Added code for traversal in a binary tree

- BMI.c
> Created BMI.c

- DeepaSubramanyam/GreatestEvenNumberedWordInString.c
Added program to find greatest even numbered word in sentence
Thank you
> Add. find greatest even numbered word in sentence

- armstrong number.cpp
Please accept my PR and also add hacktoberfest accepted label.
> Armstrong number

- Stack/Infix_to_Postfix.c
Please accept it and label as hacktoberfest accepted.
If any changes required Please GUIDE ME :-)
> (hacktoberfest2022)Create Infix_to_Postfix.c

- YearsConversion.c
Program to covert Years into Seconds,Minutes,Hours,Days and Months.
> YearsConversion.c

- Greaterof6num.c
Program to find greater of 6 numbers.
> Greaterof6num.c

- Swapping of numbers
> Swapping of numbers

- Print odd numbers from 1 to n
Print odd numbers from 1 to n using for loop
> Print odd numbers from 1 to n

- QUADRATIC EUATION ROOTS
Program to calculate roots of quadratic equation
> Quadratic Equation Roots

- SIMPLE INTREST
Program to calculate Simple Intrest
> SIMPLE INTREST

- DeepaSubramanyam/MergeInterval.cpp
Added program to merge overlapping interval in unsorted array.
Thank you
> Add. merge overlapping intervals

- length_of_largest_subarray_with_sum_zero.cpp
added program for length of largest subarray with sum zero.
thank you.
>  Add. length of largest subarray with sum zero

- C Patterns/HeartPattern.c
This is a C language code for heart pattern
> Heart shape pattern creating with C language

- getPowerNum/GetPowerNum.c
get power of number using recusion function
>  GetPowerNum.c

- Decimal To Binary/DecimalToBinary.c
>  DecimalToBinary.c

- C Patterns/XMasTree.c
Here for code from C language to create a X-Mas tree pattern
> X-Mas tree pattern using C language

- AddTwoDistances.c
- DifferenceBwTwoTimePeriods.c
Please accept my Pull request.
> Difference Between two time periods

- checkOddOrEven/checkEvenorOdd.c
- sumOfArrayElements/sumOfArrayElements.c
this is c program for sum of the array elements
> My branch 2

- checkOddOrEven/checkEvenorOdd.c
this is c program for check a number odd or even
> check odd and even

- Floyd.c
- HeartShapePattern.c
Please accept my pull request.
> added floyd's triangle

- ParallelPatterns/ParallelRight.c
contains the right aligned parallel patterns
> Right aligned patterns

- Decimal To Binary/binary.c
- Linked List/linkedlist.c
- fibonacci/Tcodet.c
- leapYear/leap.c
> Linkedlist

- checkPrime/checkPrime.c
- findFactorial/findFactorial.c
this is a c program for get factorial
> Find Factorial

- checkPrime/checkPrime.c
this is c program to check a number prime or not
> check prime

- C Patterns/MatrixTranspose.c
C code to get transpose of a matrix
> MatrixTranspose

- Remove Blank space from String
Have added a code for removing blank space from a string with C Language.
> Remove Blank space from String

- C Patterns/MatrixTranspose.c
- C Patterns/elecbill.c
C code to calculate electricity bill
> Cal elec bill

- FibonacciSeries/Fib.c
We can find fibonacci series using this code
> fibonacci program

- frequency_of_a_substring_in_main_string.c
changed code for problem "frequency of a substring in main string"
thank you.
> frequency of a substring in main string

- hello.c
> pls merge it 

- Algo Sh/prims.c
- Algo Sh/quicksort.c
> Prims Algorithm

- Algorithms Sh/prims.c
- graphics.c
This contains the inner rectangle hollow star pattern
> inner rectangle hollow star pattern

- oddOrEven/oddEven.c
Add a c programming file to check the integer odd or even
> To find integer is odd or even

- Algo Sh/pancake.c
> Pancake algorithm

- Algo Sh/shaker.c
Consists the c implementation for shaker sort
> Shaker sort

- Array/find the sum of the array.c
> Create find the sum of the array.c
